### ISSUE TITLE
Unable to run on simulator (possibly device also?)

### ISSUE THREAD

**Issue by CBDev1** [Beanstream/beanstream-ios-payform-demo#1]
installed PayForm pod 0.3.1, however the app does not run on simulator, I do not have a device to try on. Running with cocoa pods version 1.0.1, Xcode 7.3.1

2016-10-08 14:35:34.135 PayFormTest[967:11795] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'PayForm' in bundle NSBundle </Users/{user}/Library/Developer/CoreSimulator/Devices/B86BCF6C-913C-4509-9946-5CACC35CB812/data/Containers/Bundle/Application/2D53F30F-B33E-4050-BD5B-E4EE01CEF212/PayFormTest.app/Frameworks/PayForm.framework> (loaded)'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010c7abd85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010e552deb objc_exception_throw + 48
    2   UIKit                               0x000000010d717d3d -[UIStoryboard name] + 0
    3   PayFormTest                         0x000000010c50dbc1 _TTOFCSo12UIStoryboardCfT4nameSS6bundleGSqCSo8NSBundle__S_ + 81
    4   PayFormTest                         0x000000010c50c9f7 _TFC11PayFormTest14ViewController12buttonActionfPs9AnyObject_T_ + 263
    5   PayFormTest                         0x000000010c50d236 _TToFC11PayFormTest14ViewController12buttonActionfPs9AnyObject_T_ + 54
    6   UIKit                               0x000000010cfd7a8d -[UIApplication sendAction:to:from:forEvent:] + 92
    7   UIKit                               0x000000010d14ae67 -[UIControl sendAction:to:forEvent:] + 67
    8   UIKit                               0x000000010d14b143 -[UIControl _sendActionsForEvents:withEvent:] + 327
    9   UIKit                               0x000000010d14a263 -[UIControl touchesEnded:withEvent:] + 601
    10  UIKit                               0x000000010d04a99f -[UIWindow _sendTouchesForEvent:] + 835
    11  UIKit                               0x000000010d04b6d4 -[UIWindow sendEvent:] + 865
    12  UIKit                               0x000000010cff6dc6 -[UIApplication sendEvent:] + 263
    13  UIKit                               0x000000010cfd0553 _UIApplicationHandleEventQueue + 6660
    14  CoreFoundation                      0x000000010c6d1301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    15  CoreFoundation                      0x000000010c6c722c __CFRunLoopDoSources0 + 556
    16  CoreFoundation                      0x000000010c6c66e3 __CFRunLoopRun + 867
    17  CoreFoundation                      0x000000010c6c60f8 CFRunLoopRunSpecific + 488
    18  GraphicsServices                    0x0000000111f22ad2 GSEventRunModal + 161
    19  UIKit                               0x000000010cfd5f09 UIApplicationMain + 171
    20  PayFormTest                         0x000000010c510282 main + 114
    21  libdyld.dylib                       0x00000001106c092d start + 1
    22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dlight-bean** [comment]
This was resolved in version 0.3.2 of the PayForm
